const trimTrailingSlash = (s: string) => s.replace(/\/+$/, "");

export type CreatePullRequestParams = {
  apiBaseUrl: string;
  apiKey: string;
  repoFullName: string;
  branchName: string;
  baseBranch: string;
  taskId: string;
  title: string;
  summary: string;
  filesChanged: string[];
  workItemId?: string;
  isDraft?: boolean;
};

const buildPrBody = (p: CreatePullRequestParams): string => {
  const lines: string[] = [];
  lines.push(`> Generated by AI Agent`);
  lines.push("");
  lines.push("## Summary");
  lines.push(p.summary.trim() ? p.summary.trim() : "(no summary)");
  lines.push("");

  if (p.workItemId) {
    const url = `${trimTrailingSlash(p.apiBaseUrl)}/api/work-items/${p.workItemId}`;
    lines.push("## Almirant");
    lines.push(`- Work item: ${url}`);
    lines.push("");
  }

  if (p.filesChanged.length) {
    lines.push("## Files changed");
    for (const f of p.filesChanged.slice(0, 200)) {
      lines.push("- `" + f + "`");
    }
    if (p.filesChanged.length > 200) lines.push(`- (and ${p.filesChanged.length - 200} more)`);
    lines.push("");
  }

  return lines.join("\n");
};

export const createPullRequest = async (p: CreatePullRequestParams): Promise<{ prUrl: string; prNumber: number; prId: string }> => {
  const url = `${trimTrailingSlash(p.apiBaseUrl)}/api/github/pull-requests`;

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": p.apiKey,
    },
    body: JSON.stringify({
      repoFullName: p.repoFullName,
      head: p.branchName,
      base: p.baseBranch,
      title: `[${p.taskId}] ${p.title}`,
      body: buildPrBody(p),
      ...(p.isDraft ? { isDraft: true } : {}),
    }),
  });

  const raw = await res.text().catch(() => "");
  let payload: unknown = null;
  if (raw) {
    try {
      payload = JSON.parse(raw) as unknown;
    } catch {
      payload = null;
    }
  }

  if (!res.ok) {
    const msg =
      typeof payload === "object" && payload && "error" in payload ? String((payload as any).error) : raw;
    throw new Error(`MC API PR create failed: HTTP ${res.status} ${res.statusText}${msg ? `: ${msg}` : ""}`);
  }

  const data = (payload as any)?.data ?? (payload as any);
  const prUrl = data?.prUrl;
  const prNumber = data?.prNumber;
  const prId = data?.prId;

  if (typeof prUrl !== "string" || typeof prNumber !== "number" || typeof prId !== "string") {
    throw new Error("MC API PR create returned unexpected payload");
  }

  return { prUrl, prNumber, prId };
};
