// This file is generated by scripts/generate-runtime-capability-projection.ts.
// Do not edit it by hand; update runtime-capability-registry.ts and regenerate.
export const runtimeCapabilityProjection = {
  "aiProviders": [
    "anthropic",
    "google",
    "openai",
    "xai",
    "zai"
  ],
  "authClasses": [
    "api_key",
    "provider_oauth",
    "setup_token",
    "subscription"
  ],
  "authPolicies": [
    {
      "authClass": "api_key",
      "codingAgent": "pi",
      "enabled": true,
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "authClass": "provider_oauth",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_AUTH_PROVIDER_OAUTH_DISABLED",
      "runtimeVerified": false
    },
    {
      "authClass": "setup_token",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_AUTH_SETUP_TOKEN_DISABLED",
      "runtimeVerified": false
    },
    {
      "authClass": "subscription",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_AUTH_SUBSCRIPTION_DISABLED",
      "runtimeVerified": false
    }
  ],
  "capabilityIds": [
    "browser",
    "extensions",
    "mcp",
    "permission_enforced",
    "read_only_enforced",
    "sandbox"
  ],
  "capabilityPolicies": [
    {
      "capability": "browser",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_CAPABILITY_BROWSER_DISABLED",
      "runtimeVerified": false
    },
    {
      "capability": "extensions",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_CAPABILITY_EXTENSIONS_DISABLED",
      "runtimeVerified": false
    },
    {
      "capability": "mcp",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_CAPABILITY_MCP_DISABLED",
      "runtimeVerified": false
    },
    {
      "capability": "permission_enforced",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_CAPABILITY_PERMISSION_ENFORCEMENT_DISABLED",
      "runtimeVerified": false
    },
    {
      "capability": "read_only_enforced",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_CAPABILITY_READ_ONLY_ENFORCEMENT_DISABLED",
      "runtimeVerified": false
    },
    {
      "capability": "sandbox",
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_CAPABILITY_SANDBOX_DISABLED",
      "runtimeVerified": false
    }
  ],
  "codingAgents": [
    "claude-code",
    "codex",
    "opencode",
    "pi"
  ],
  "customProviderPolicies": [
    {
      "codingAgent": "pi",
      "enabled": false,
      "rejectionCode": "PI_CUSTOM_PROVIDER_DISABLED",
      "runtimeVerified": false
    }
  ],
  "defaults": [
    {
      "aiProvider": "anthropic",
      "model": "claude-opus-5"
    },
    {
      "aiProvider": "google",
      "model": "gemini-3.1-pro-preview"
    },
    {
      "aiProvider": "openai",
      "model": "gpt-5.6-sol"
    },
    {
      "aiProvider": "xai",
      "model": "grok-4.3"
    },
    {
      "aiProvider": "zai",
      "model": "glm-5.2"
    }
  ],
  "hash": "sha256:327220bb9a782191ac2f13a8cdd407cd3556d2fbabd2b30f92766f9ffcebc51f",
  "rejectionCodes": [
    "PI_AUTH_PROVIDER_OAUTH_DISABLED",
    "PI_AUTH_SETUP_TOKEN_DISABLED",
    "PI_AUTH_SUBSCRIPTION_DISABLED",
    "PI_CAPABILITY_BROWSER_DISABLED",
    "PI_CAPABILITY_EXTENSIONS_DISABLED",
    "PI_CAPABILITY_MCP_DISABLED",
    "PI_CAPABILITY_PERMISSION_ENFORCEMENT_DISABLED",
    "PI_CAPABILITY_READ_ONLY_ENFORCEMENT_DISABLED",
    "PI_CAPABILITY_SANDBOX_DISABLED",
    "PI_CUSTOM_PROVIDER_DISABLED",
    "RUNTIME_ADMISSION_DISABLED",
    "RUNTIME_AI_PROVIDER_UNSUPPORTED",
    "RUNTIME_AUTH_CLASS_UNSUPPORTED",
    "RUNTIME_CAPABILITY_UNSUPPORTED",
    "RUNTIME_CODING_AGENT_UNSUPPORTED",
    "RUNTIME_MODEL_UNSUPPORTED",
    "RUNTIME_REGISTRY_HASH_MISMATCH",
    "RUNTIME_REGISTRY_VERSION_MISMATCH"
  ],
  "schemaVersion": "runtime-capability-projection-v1",
  "tuples": [
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-fable-5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-haiku-4-5",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-opus-4-5",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-opus-4-6",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-opus-4-7",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-opus-4-8",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-opus-5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-sonnet-4-5",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-sonnet-4-6",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "claude-sonnet-5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-4.5",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-4.5-air",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-4.6",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-4.7",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-5",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-5-turbo",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-5.1",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-5.2",
      "reasoningEfforts": [
        "high",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "claude-code",
      "model": "glm-5.3",
      "reasoningEfforts": [
        "high",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-4.1",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-4.1-mini",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.3-codex",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.4",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.4-mini",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.4-nano",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.4-pro",
      "reasoningEfforts": [
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.5-pro",
      "reasoningEfforts": [
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.6",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.6-luna",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.6-sol",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "codex",
      "model": "gpt-5.6-terra",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-4.1",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-4.1-mini",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.3-codex",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.4",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.4-mini",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.4-nano",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.4-pro",
      "reasoningEfforts": [
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.5-pro",
      "reasoningEfforts": [
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.6",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.6-luna",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.6-sol",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "openai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "gpt-5.6-terra",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "xai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "grok-4.20",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "xai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "grok-4.20-multi-agent",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "xai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "grok-4.20-reasoning",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "xai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "grok-4.3",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "xai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "grok-build-0.1",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-4.5",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-4.5-air",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-4.6",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-4.7",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-5",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-5-turbo",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-5.1",
      "reasoningEfforts": [],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-5.2",
      "reasoningEfforts": [
        "high",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key",
        "provider_oauth",
        "setup_token",
        "subscription"
      ],
      "codingAgent": "opencode",
      "model": "glm-5.3",
      "reasoningEfforts": [
        "high",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    },
    {
      "admissionEnabled": false,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "claude-fable-5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "claude-haiku-4-5",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "claude-opus-4-7",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "claude-opus-4-8",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "claude-opus-5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "anthropic",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "claude-sonnet-5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "google",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gemini-2.5-flash",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "google",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gemini-2.5-flash-lite",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "google",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gemini-2.5-pro",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "google",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gemini-3-flash-preview",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "google",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gemini-3.1-flash-lite",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "google",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gemini-3.1-pro-preview",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "google",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gemini-3.5-flash",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-4.1",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-4.1-mini",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.3-codex",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.4",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.4-mini",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.4-nano",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.4-pro",
      "reasoningEfforts": [
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.5",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.5-pro",
      "reasoningEfforts": [
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.6-luna",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.6-sol",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "openai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "gpt-5.6-terra",
      "reasoningEfforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "xai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "grok-4.3",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "xai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "grok-build-0.1",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "zai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "glm-4.7",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "zai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "glm-5-turbo",
      "reasoningEfforts": [],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": false,
      "aiProvider": "zai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "glm-5.2",
      "reasoningEfforts": [
        "high",
        "max"
      ],
      "rejectionCode": "RUNTIME_ADMISSION_DISABLED",
      "runtimeVerified": false
    },
    {
      "admissionEnabled": true,
      "aiProvider": "zai",
      "authClasses": [
        "api_key"
      ],
      "codingAgent": "pi",
      "model": "glm-5.3",
      "reasoningEfforts": [
        "high",
        "max"
      ],
      "rejectionCode": null,
      "runtimeVerified": true
    }
  ],
  "version": 1
} as const;

export type RuntimeCapabilityProjectionGenerated =
  typeof runtimeCapabilityProjection;
