import type { GoalMeetingDataset } from "./types";

export const MVP_LAUNCH_GOAL_DATA: GoalMeetingDataset = {
  goalTitle: "Lanzar MVP en produccion",
  goalDescription:
    "Objetivo de corto plazo: salir a mercado con MVP funcional para solopreneurs Build in Public.",
  startDate: "2026-02-22",
  targetDate: "2026-03-01",
  lastUpdated: "2026-02-22",
  successCriteria: [
    "Worker desplegado en VPS con guia operativa clara.",
    "Flujo completo validado en produccion: user -> enqueue -> worker -> PR.",
    "Share to Twitter disponible via copy-to-clipboard.",
    "Captura por voz en Telegram transcrita con Whisper.",
  ],
  measurementNotes: [
    "El avance principal se calcula sobre items requeridos para launch.",
    "Bloque C queda como diferenciador post-lanzamiento.",
  ],
  readinessAreas: [
    {
      id: "cloud-execution",
      title: "Pieza 1: Ejecucion cloud",
      progress: 90,
      note: "Motor tecnico listo, faltan capa operativa y despliegue.",
    },
    {
      id: "conversational-planning",
      title: "Pieza 2: Planning conversacional",
      progress: 60,
      note: "Texto operativo, voz pendiente para caso movil.",
    },
    {
      id: "share-to-twitter",
      title: "Pieza 3: Share to Twitter",
      progress: 30,
      note: "Base de contenido disponible, falta output de sharing.",
    },
    {
      id: "platform-base",
      title: "Plataforma base",
      progress: 92,
      note: "Base productiva, con deuda de testing/operaciones.",
    },
  ],
  todoItems: [
    {
      id: "deploy-worker-vps",
      title: "Deploy worker en VPS con guia y scripts",
      description:
        "Documentar y validar un procedimiento reproducible de despliegue para el worker.",
      block: "A",
      requiredForLaunch: true,
      weight: 25,
      status: "in_progress",
      progress: 35,
      risk: "medium",
      targetDate: "2026-02-24",
    },
    {
      id: "validate-e2e-production",
      title: "Validar flujo end-to-end en produccion",
      description:
        "Ejecutar y evidenciar el flujo completo desde usuario hasta PR creada.",
      block: "A",
      requiredForLaunch: true,
      weight: 25,
      status: "planned",
      progress: 0,
      risk: "high",
      targetDate: "2026-02-26",
    },
    {
      id: "share-to-twitter-copy",
      title: "Boton Share to Twitter con copy-to-clipboard",
      description:
        "Formatear hilo y copiar al portapapeles sin depender de API de X.",
      block: "B",
      requiredForLaunch: true,
      weight: 20,
      status: "planned",
      progress: 0,
      risk: "medium",
      targetDate: "2026-02-27",
    },
    {
      id: "telegram-voice-whisper",
      title: "Voice messages Telegram + transcripcion Whisper",
      description:
        "Convertir audio a texto para crear items desde movilidad.",
      block: "B",
      requiredForLaunch: true,
      weight: 20,
      status: "planned",
      progress: 0,
      risk: "medium",
      targetDate: "2026-02-27",
    },
    {
      id: "launch-stability-checklist",
      title: "Checklist minima de estabilidad para launch",
      description:
        "Smoke checks de flujo principal y observabilidad basica de operacion.",
      block: "B",
      requiredForLaunch: true,
      weight: 10,
      status: "in_progress",
      progress: 20,
      risk: "medium",
      targetDate: "2026-02-28",
    },
    {
      id: "discord-bot",
      title: "Discord bot",
      description: "Replica del flujo de Telegram para planning conversacional.",
      block: "C",
      requiredForLaunch: false,
      weight: 15,
      status: "planned",
      progress: 0,
      risk: "low",
      targetDate: "2026-03-10",
    },
    {
      id: "twitter-api-autopost",
      title: "Integracion directa con Twitter API",
      description: "Automatizar publicacion del hilo sin paso manual.",
      block: "C",
      requiredForLaunch: false,
      weight: 15,
      status: "planned",
      progress: 0,
      risk: "low",
      targetDate: "2026-03-15",
    },
    {
      id: "weekly-summary-scheduler",
      title: "Resumen semanal automatico",
      description: "Scheduler para digest periodico y previsualizacion.",
      block: "C",
      requiredForLaunch: false,
      weight: 15,
      status: "planned",
      progress: 0,
      risk: "low",
      targetDate: "2026-03-15",
    },
  ],
};
