#!/usr/bin/env node

/**
 * @almirant/connect CLI
 *
 * Usage:
 *   npx @almirant/connect <provider> --token <link-token> [--api-url <url>]
 *
 * Supported providers: claude, codex
 *
 * The link token is a one-time token generated by the Almirant dashboard.
 * After the provider-specific auth flow completes, the collected credentials
 * are posted back to the Almirant API to finalise the connection.
 */

import { connectClaude } from "./providers/claude.js";
import { connectCodex } from "./providers/codex.js";
import { completeLinkToken } from "./api.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ParsedArgs {
  provider: string;
  linkToken: string;
  apiUrl: string;
}

type ProviderFn = () => Promise<Record<string, unknown>>;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEFAULT_API_URL = "https://api.almirant.ai";

const SUPPORTED_PROVIDERS: Record<string, ProviderFn> = {
  claude: connectClaude,
  codex: connectCodex,
};

const USAGE = `
  @almirant/connect - Connect AI subscriptions with Almirant

  Usage:
    npx @almirant/connect <provider> --token <link-token> [--api-url <url>]

  Providers:
    claude    Deprecated: connect Claude Max from the dashboard OAuth flow
    codex     Connect a ChatGPT Pro / Codex subscription

  Options:
    --token <token>    One-time link token from the Almirant dashboard (required)
    --api-url <url>    Almirant API base URL (default: ${DEFAULT_API_URL})
    --help             Show this help message

  Examples:
    npx @almirant/connect claude --token abc123
    npx @almirant/connect codex  --token abc123 --api-url http://localhost:3001
`.trimStart();

// ---------------------------------------------------------------------------
// Arg parsing
// ---------------------------------------------------------------------------

const parseArgs = (argv: string[]): ParsedArgs => {
  // Strip the node binary and script path.
  const args = argv.slice(2);

  if (args.includes("--help") || args.includes("-h") || args.length === 0) {
    console.log(USAGE);
    process.exit(0);
  }

  const provider = args[0];
  if (!provider || provider.startsWith("-")) {
    console.error("[!] Error: provider is required as the first argument.\n");
    console.log(USAGE);
    process.exit(1);
  }

  if (!SUPPORTED_PROVIDERS[provider]) {
    console.error(
      `[!] Error: unknown provider "${provider}".\n` +
        `    Supported: ${Object.keys(SUPPORTED_PROVIDERS).join(", ")}\n`,
    );
    process.exit(1);
  }

  let linkToken: string | undefined;
  let apiUrl = DEFAULT_API_URL;

  for (let i = 1; i < args.length; i++) {
    const arg = args[i];

    if (arg === "--token" || arg === "-t") {
      linkToken = args[++i];
      if (!linkToken) {
        console.error("[!] Error: --token requires a value.\n");
        process.exit(1);
      }
      continue;
    }

    if (arg === "--api-url") {
      apiUrl = args[++i];
      if (!apiUrl) {
        console.error("[!] Error: --api-url requires a value.\n");
        process.exit(1);
      }
      continue;
    }

    console.error(`[!] Error: unknown option "${arg}".\n`);
    console.log(USAGE);
    process.exit(1);
  }

  if (!linkToken) {
    console.error("[!] Error: --token is required.\n");
    console.log(USAGE);
    process.exit(1);
  }

  return { provider, linkToken, apiUrl };
};

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const main = async (): Promise<void> => {
  const { provider, linkToken, apiUrl } = parseArgs(process.argv);

  console.log(`[@almirant/connect] Provider: ${provider}`);
  console.log(`[@almirant/connect] API URL:  ${apiUrl}`);
  console.log();

  // Run the provider-specific auth flow.
  const providerFn = SUPPORTED_PROVIDERS[provider];
  if (!providerFn) {
    // Should not happen after parseArgs, but satisfies the type checker.
    throw new Error(`No handler for provider "${provider}".`);
  }

  const credentials = await providerFn();

  // Post credentials back to Almirant.
  console.log();
  console.log("[*] Sending credentials to Almirant...");

  await completeLinkToken(apiUrl, linkToken, credentials);

  console.log("[+] Connection established successfully!");
  console.log(
    "    You can close this terminal and return to the Almirant dashboard.",
  );
};

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

main().catch((err: unknown) => {
  const message = err instanceof Error ? err.message : String(err);
  console.error();
  console.error(`[!] ${message}`);
  process.exit(1);
});
