#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${SHIM_ENTRY:-}" ]]; then
  echo "SHIM_ENTRY is required"
  exit 1
fi

TARGET_DIR="${WORKSPACE_REPO_PATH:-/workspace/repo}"

CLONE_TIMEOUT="${CLONE_TIMEOUT_SECONDS:-120}"
WORKSPACE_KIND="${WORKSPACE_KIND:-}"
if [[ -z "$WORKSPACE_KIND" ]]; then
  if [[ -n "${REPO_URL:-}" ]]; then
    WORKSPACE_KIND="git_repo"
  else
    WORKSPACE_KIND="empty_workspace"
  fi
fi

case "$WORKSPACE_KIND" in
  git_repo)
    if [[ -z "${REPO_URL:-}" ]]; then
      echo "[entrypoint] ERROR: WORKSPACE_KIND=git_repo requires REPO_URL"
      exit 1
    fi

    rm -rf "$TARGET_DIR"
    CLONE_DEPTH="${GIT_CLONE_DEPTH:-1}"

    if [[ -n "${__GIT_CLONE_TOKEN:-}" ]]; then
      # Use GIT_ASKPASS for the initial clone.
      export GIT_ASKPASS="/tmp/git-askpass.sh"
      printf '#!/bin/sh
echo "%s"
' "$__GIT_CLONE_TOKEN" > "$GIT_ASKPASS"
      chmod +x "$GIT_ASKPASS"
      echo "[entrypoint] Cloning ${REPO_URL} (branch: ${REPO_BRANCH:-main}, depth: ${CLONE_DEPTH}) with auth token..."
      timeout "${CLONE_TIMEOUT}" git clone --depth "$CLONE_DEPTH" --branch "${REPO_BRANCH:-main}" "$REPO_URL" "$TARGET_DIR" || {
        echo "[entrypoint] ERROR: git clone failed or timed out after ${CLONE_TIMEOUT}s"
        exit 1
      }

      # Configure git credential helper so the token persists across all shells.
      printf '#!/bin/sh
echo "username=x-access-token"
echo "password=%s"
' "$__GIT_CLONE_TOKEN" > /tmp/git-credential-almirant.sh
      chmod +x /tmp/git-credential-almirant.sh
      git config --global credential.helper '!/tmp/git-credential-almirant.sh'

      # Persist the GitHub token outside the parent process env so fresh shells
      # (bash -lc / zsh -lc) can resolve the latest token for gh CLI commands.
      printf '%s' "$__GIT_CLONE_TOKEN" > /tmp/github-token
      chmod 600 /tmp/github-token
      cat > /tmp/load-github-token-env.sh <<'EOF'
if [ -f /tmp/github-token ]; then
  export GH_TOKEN="$(cat /tmp/github-token)"
  export GITHUB_TOKEN="$GH_TOKEN"
fi
EOF
      chmod 755 /tmp/load-github-token-env.sh
      export GH_TOKEN="$__GIT_CLONE_TOKEN"
      export GITHUB_TOKEN="$__GIT_CLONE_TOKEN"

      for shell_rc in /home/opencode/.bashrc /home/opencode/.bash_profile /home/opencode/.profile /home/opencode/.zshrc /home/opencode/.zprofile; do
        echo "export GIT_ASKPASS=/tmp/git-askpass.sh" >> "$shell_rc" 2>/dev/null || true
        echo '[ -f /tmp/load-github-token-env.sh ] && . /tmp/load-github-token-env.sh' >> "$shell_rc" 2>/dev/null || true
      done

      unset __GIT_CLONE_TOKEN
    else
      echo "[entrypoint] WARNING: No __GIT_CLONE_TOKEN set. Cloning ${REPO_URL} without auth (will fail for private repos)..."
      # Use GIT_TERMINAL_PROMPT=0 to prevent git from hanging waiting for credentials
      export GIT_TERMINAL_PROMPT=0
      timeout "${CLONE_TIMEOUT}" git clone --depth "$CLONE_DEPTH" --branch "${REPO_BRANCH:-main}" "$REPO_URL" "$TARGET_DIR" || {
        echo "[entrypoint] ERROR: git clone failed (likely private repo without auth token). Timed out after ${CLONE_TIMEOUT}s."
        exit 1
      }
    fi
    ;;
  empty_workspace|uploaded_files)
    mkdir -p "$TARGET_DIR"
    ;;
  *)
    echo "[entrypoint] ERROR: unsupported WORKSPACE_KIND=${WORKSPACE_KIND}"
    exit 1
    ;;
esac

mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"

# Runtime config files are generated by the runner for the container only.
# Keep them out of agent commits even when skills run `git add -A`.

mark_runner_managed_path() {
  local path="$1"

  if [[ -z "$path" ]] || ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    return 0
  fi

  if git ls-files --error-unmatch -- "$path" >/dev/null 2>&1; then
    git update-index --assume-unchanged -- "$path" 2>/dev/null || true
    return 0
  fi

  local exclude_file
  exclude_file="$(git rev-parse --git-path info/exclude 2>/dev/null || true)"
  if [[ -z "$exclude_file" ]]; then
    return 0
  fi

  mkdir -p "$(dirname "$exclude_file")"
  touch "$exclude_file"
  grep -Fxq "/$path" "$exclude_file" 2>/dev/null || printf '/%s\n' "$path" >> "$exclude_file"
}


# Ensure platform skills from main are available.
# Feature branches created before a skill was added won't have the skill files.
# Fetch main (shallow) and overlay .claude/skills/ so all skills are current.
# Reset after checkout to unstage — keeps files in working tree but not in the
# git index, so subsequent commits by the agent don't accidentally include them.
if [[ -d "$TARGET_DIR/.git" ]] && [[ "${REPO_BRANCH:-main}" != "main" ]]; then
  git -C "$TARGET_DIR" fetch origin main --depth=1 2>/dev/null || true
  git -C "$TARGET_DIR" checkout FETCH_HEAD -- .claude/skills/ 2>/dev/null || true
  git -C "$TARGET_DIR" reset HEAD -- .claude/skills/ 2>/dev/null || true
fi

# Start Xvfb virtual framebuffer for browser-based recording sessions
if [ "${ENABLE_BROWSER:-false}" = "true" ]; then
  Xvfb :99 -screen 0 1920x1080x24 -ac &
  export DISPLAY=:99
fi

# Configure git identity as the GitHub App bot
git config --global user.name "almirant-ai[bot]"
git config --global user.email "263330516+almirant-ai[bot]@users.noreply.github.com"

# Write Codex auth.json from env var (subscription tokens)
if [[ -n "${CODEX_AUTH_JSON:-}" ]]; then
  mkdir -p /home/opencode/.codex
  printf '%s' "$CODEX_AUTH_JSON" > /home/opencode/.codex/auth.json
  chmod 0600 /home/opencode/.codex/auth.json
  unset CODEX_AUTH_JSON
fi

# Write Codex MCP server config to ~/.codex/config.toml
if [[ -n "${CODEX_MCP_JSON:-}" ]]; then
  mkdir -p /home/opencode/.codex
  CONFIG_FILE="/home/opencode/.codex/config.toml"

  # Iterate over each MCP server entry and write TOML sections
  for SERVER_NAME in $(echo "$CODEX_MCP_JSON" | jq -r 'keys[]'); do
    echo "" >> "$CONFIG_FILE"
    echo "[mcp_servers.\"${SERVER_NAME}\"]" >> "$CONFIG_FILE"

    SERVER_JSON=$(echo "$CODEX_MCP_JSON" | jq -c --arg name "$SERVER_NAME" '.[$name]')

    # Check if it's a remote (has url) or local (has command) server
    URL=$(echo "$SERVER_JSON" | jq -r '.url // empty')
    COMMAND=$(echo "$SERVER_JSON" | jq -r '.command // empty')

    if [[ -n "$URL" ]]; then
      echo "url = \"${URL}\"" >> "$CONFIG_FILE"
      BEARER_VAR=$(echo "$SERVER_JSON" | jq -r '.bearer_token_env_var // empty')
      if [[ -n "$BEARER_VAR" ]]; then
        echo "bearer_token_env_var = \"${BEARER_VAR}\"" >> "$CONFIG_FILE"
      fi
    elif [[ -n "$COMMAND" ]]; then
      echo "command = \"${COMMAND}\"" >> "$CONFIG_FILE"
      # Write args as TOML array
      ARGS=$(echo "$SERVER_JSON" | jq -c '.args // []')
      if [[ "$ARGS" != "[]" ]]; then
        # Convert JSON array to TOML array: ["a","b"] -> ["a", "b"]
        TOML_ARGS=$(echo "$ARGS" | jq -r '[.[] | "\"" + . + "\""] | join(", ")')
        echo "args = [${TOML_ARGS}]" >> "$CONFIG_FILE"
      fi
    fi
  done

  echo "[entrypoint] Wrote MCP config to $CONFIG_FILE ($(echo "$CODEX_MCP_JSON" | jq 'keys | length') servers)"
  unset CODEX_MCP_JSON
fi

# visual_judge never receives MCP. Materialize a runner-owned empty config
# outside the repository so --strict-mcp-config has one explicit source and
# cannot fall back to a repo-controlled .mcp.json. The shim also validates this
# file and probes --safe-mode support before spawning Claude.
if [[ "${ALMIRANT_CLAUDE_TOOL_POLICY:-}" == "read-only" ]]; then
  READ_ONLY_CLAUDE_MCP_CONFIG="/tmp/almirant-visual-judge-mcp.json"
  READ_ONLY_CLAUDE_CONFIG_DIR="/tmp/almirant-visual-judge-claude"
  rm -rf "$READ_ONLY_CLAUDE_CONFIG_DIR"
  mkdir -p -m 0700 "$READ_ONLY_CLAUDE_CONFIG_DIR"
  printf '%s' '{"mcpServers":{}}' > "$READ_ONLY_CLAUDE_MCP_CONFIG"
  chmod 0400 "$READ_ONLY_CLAUDE_MCP_CONFIG"
  export CLAUDE_CODE_SAFE_MODE=1
  export CLAUDE_CONFIG_DIR="$READ_ONLY_CLAUDE_CONFIG_DIR"
  unset CLAUDE_MCP_JSON
# Write Claude Code MCP config and settings for normal Claude shim containers.
elif [[ -n "${CLAUDE_MCP_JSON:-}" ]]; then
  printf '%s' "$CLAUDE_MCP_JSON" > "$TARGET_DIR/.mcp.json"
  mark_runner_managed_path ".mcp.json"

  mkdir -p "$TARGET_DIR/.claude"
  MCP_PERMISSION_ALLOW=$(echo "$CLAUDE_MCP_JSON" | jq -c '
      [
        "Bash(*)",
        "Read",
        "Edit",
        "Write",
        "Glob",
        "Grep",
        "WebFetch",
        "WebSearch",
        "NotebookEdit"
      ] + (
        .mcpServers
        | keys
        | map(["mcp__" + . + "__*", "mcp__" + (gsub("[^A-Za-z0-9_]"; "_")) + "__*"])
        | flatten
      ) | unique
    ')
  cat > "$TARGET_DIR/.claude/settings.json" <<SETTINGS
{"permissions":{"allow":${MCP_PERMISSION_ALLOW}}}
SETTINGS

  mark_runner_managed_path ".claude/settings.json"

  unset CLAUDE_MCP_JSON
fi

# Claude Code reads provider configuration from process env, but Z.AI's
# official Claude Code guide configures the same values through the user-level
# ~/.claude/settings.json. Mirror the injected runtime env there as well so
# non-interactive runner sessions and any Claude Code child process observe the
# exact same Anthropic-compatible Z.AI configuration.
#
# IMPORTANT: keep secrets out of the repository workspace. The project-level
# .claude/settings.json above contains permissions only; provider credentials
# are written under $HOME instead.
if [[ -n "${ANTHROPIC_AUTH_TOKEN:-}" || -n "${ANTHROPIC_BASE_URL:-}" || -n "${CLAUDE_CODE_SUBAGENT_MODEL:-}" ]]; then
  CLAUDE_USER_SETTINGS_DIR="${HOME:-/home/opencode}/.claude"
  mkdir -p "$CLAUDE_USER_SETTINGS_DIR"
  jq -n \
    --arg auth_token "${ANTHROPIC_AUTH_TOKEN:-}" \
    --arg base_url "${ANTHROPIC_BASE_URL:-}" \
    --arg api_timeout "${API_TIMEOUT_MS:-}" \
    --arg opus_model "${ANTHROPIC_DEFAULT_OPUS_MODEL:-}" \
    --arg sonnet_model "${ANTHROPIC_DEFAULT_SONNET_MODEL:-}" \
    --arg haiku_model "${ANTHROPIC_DEFAULT_HAIKU_MODEL:-}" \
    --arg subagent_model "${CLAUDE_CODE_SUBAGENT_MODEL:-}" \
    --arg disable_nonessential "${CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:-}" \
    '
      def env_value($key; $value):
        if $value == "" then {} else {($key): $value} end;

      {
        env: (
          env_value("ANTHROPIC_AUTH_TOKEN"; $auth_token)
          + env_value("ANTHROPIC_BASE_URL"; $base_url)
          + env_value("API_TIMEOUT_MS"; $api_timeout)
          + env_value("CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC"; $disable_nonessential)
          + env_value("ANTHROPIC_DEFAULT_OPUS_MODEL"; $opus_model)
          + env_value("ANTHROPIC_DEFAULT_SONNET_MODEL"; $sonnet_model)
          + env_value("ANTHROPIC_DEFAULT_HAIKU_MODEL"; $haiku_model)
          + env_value("CLAUDE_CODE_SUBAGENT_MODEL"; $subagent_model)
        )
      }
    ' > "$CLAUDE_USER_SETTINGS_DIR/settings.json"
  chmod 0600 "$CLAUDE_USER_SETTINGS_DIR/settings.json"
fi

# Patch Node.js fetch to route through HTTPS_PROXY using undici ProxyAgent.
# Without this, Claude Code's MCP HTTP connections bypass the egress proxy
# and fail (the agent network only has internet access through the proxy).
if [[ -n "${HTTPS_PROXY:-}" ]]; then
  cat > /tmp/proxy-bootstrap.cjs <<PROXYJS
try {
  const { ProxyAgent, setGlobalDispatcher } = require("/usr/local/lib/node_modules/undici");
  const proxy = "${HTTPS_PROXY}";
  const noProxy = "${NO_PROXY:-}";
  const agent = new ProxyAgent({
    uri: proxy,
    noProxy: noProxy || undefined,
  });
  setGlobalDispatcher(agent);
} catch (e) {
  console.error("[proxy-bootstrap] Failed:", e.message);
}
PROXYJS
  NODE_OPTIONS="${NODE_OPTIONS:-} -r /tmp/proxy-bootstrap.cjs"
  export NODE_OPTIONS
fi

exec bun "$SHIM_ENTRY"
