#!/usr/bin/env bash
set -euo pipefail

TARGET_DIR="${WORKSPACE_REPO_PATH:-/workspace/repo}"
WORKSPACE_KIND="${WORKSPACE_KIND:-}"
if [[ -z "$WORKSPACE_KIND" ]]; then
  if [[ -n "${REPO_URL:-}" ]]; then
    WORKSPACE_KIND="git_repo"
  else
    WORKSPACE_KIND="empty_workspace"
  fi
fi

case "$WORKSPACE_KIND" in
  git_repo)
    if [[ -z "${REPO_URL:-}" ]]; then
      echo "[entrypoint] ERROR: WORKSPACE_KIND=git_repo requires REPO_URL"
      exit 1
    fi

    rm -rf "$TARGET_DIR"
    CLONE_DEPTH="${GIT_CLONE_DEPTH:-1}"

    if [[ -n "${__GIT_CLONE_TOKEN:-}" ]]; then
      # Use GIT_ASKPASS for the initial clone.
      export GIT_ASKPASS="/tmp/git-askpass.sh"
      printf '#!/bin/sh
echo "%s"
' "$__GIT_CLONE_TOKEN" > "$GIT_ASKPASS"
      chmod +x "$GIT_ASKPASS"
      git clone --depth "$CLONE_DEPTH" --branch "${REPO_BRANCH:-main}" "$REPO_URL" "$TARGET_DIR"

      # Configure git credential helper so the token persists across all shells.
      # Agent runtimes (Claude Code, OpenCode) create fresh shells that may not
      # inherit the parent process's env vars. Using git's credential helper
      # via gitconfig ensures credentials are available in any shell context.
      printf '#!/bin/sh
echo "username=x-access-token"
echo "password=%s"
' "$__GIT_CLONE_TOKEN" > /tmp/git-credential-almirant.sh
      chmod +x /tmp/git-credential-almirant.sh
      git config --global credential.helper '!/tmp/git-credential-almirant.sh'

      printf '%s' "$__GIT_CLONE_TOKEN" > /tmp/github-token
      chmod 600 /tmp/github-token
      cat > /tmp/load-github-token-env.sh <<'EOF'
if [ -f /tmp/github-token ]; then
  export GH_TOKEN="$(cat /tmp/github-token)"
  export GITHUB_TOKEN="$GH_TOKEN"
fi
EOF
      chmod 755 /tmp/load-github-token-env.sh
      export GH_TOKEN="$__GIT_CLONE_TOKEN"
      export GITHUB_TOKEN="$__GIT_CLONE_TOKEN"

      for shell_rc in /home/opencode/.bashrc /home/opencode/.bash_profile /home/opencode/.profile /home/opencode/.zshrc /home/opencode/.zprofile; do
        echo "export GIT_ASKPASS=/tmp/git-askpass.sh" >> "$shell_rc" 2>/dev/null || true
        echo '[ -f /tmp/load-github-token-env.sh ] && . /tmp/load-github-token-env.sh' >> "$shell_rc" 2>/dev/null || true
      done

      unset __GIT_CLONE_TOKEN
    else
      git clone --depth "$CLONE_DEPTH" --branch "${REPO_BRANCH:-main}" "$REPO_URL" "$TARGET_DIR"
    fi
    ;;
  empty_workspace|uploaded_files)
    mkdir -p "$TARGET_DIR"
    ;;
  *)
    echo "[entrypoint] ERROR: unsupported WORKSPACE_KIND=${WORKSPACE_KIND}"
    exit 1
    ;;
esac

mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"

# Runtime config files are generated by the runner for the container only.
# Keep them out of agent commits even when skills run `git add -A`.

mark_runner_managed_path() {
  local path="$1"

  if [[ -z "$path" ]] || ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    return 0
  fi

  if git ls-files --error-unmatch -- "$path" >/dev/null 2>&1; then
    git update-index --assume-unchanged -- "$path" 2>/dev/null || true
    return 0
  fi

  local exclude_file
  exclude_file="$(git rev-parse --git-path info/exclude 2>/dev/null || true)"
  if [[ -z "$exclude_file" ]]; then
    return 0
  fi

  mkdir -p "$(dirname "$exclude_file")"
  touch "$exclude_file"
  grep -Fxq "/$path" "$exclude_file" 2>/dev/null || printf '/%s\n' "$path" >> "$exclude_file"
}


# Ensure platform skills from main are available.
# Feature branches created before a skill was added won't have the skill files.
# Fetch main (shallow) and overlay .agents/skills/ so all skills are current.
# Reset after checkout to unstage — keeps files in working tree but not in the
# git index, so subsequent commits by the agent don't accidentally include them.
if [[ -d "$TARGET_DIR/.git" ]] && [[ "${REPO_BRANCH:-main}" != "main" ]]; then
  git -C "$TARGET_DIR" fetch origin main --depth=1 2>/dev/null || true
  git -C "$TARGET_DIR" checkout FETCH_HEAD -- .agents/skills/ 2>/dev/null || true
  git -C "$TARGET_DIR" reset HEAD -- .agents/skills/ 2>/dev/null || true
fi

# Start Xvfb virtual framebuffer for browser-based recording sessions
if [ "${ENABLE_BROWSER:-false}" = "true" ]; then
  Xvfb :99 -screen 0 1920x1080x24 -ac &
  export DISPLAY=:99
fi

# Configure git identity as the GitHub App bot
git config --global user.name "almirant-ai[bot]"
git config --global user.email "263330516+almirant-ai[bot]@users.noreply.github.com"

if [[ -n "${OPENCODE_CONFIG_JSON:-}" ]]; then
  printf '%s' "$OPENCODE_CONFIG_JSON" > opencode.json
  mark_runner_managed_path "opencode.json"
fi

if [[ -n "${MCP_CONFIG_JSON:-}" ]]; then
  printf '%s' "$MCP_CONFIG_JSON" > .mcp.json
  mark_runner_managed_path ".mcp.json"
fi

if [[ "${OPENCODE_START_MODE:-serve}" == "run" ]]; then
  if [[ -z "${SKILL_NAME:-}" ]]; then
    echo "SKILL_NAME is required when OPENCODE_START_MODE=run"
    exit 1
  fi
  # WORK_ITEM_IDS intentionally expands to separate arguments for multi-item runs.
  # shellcheck disable=SC2086
  exec opencode run --dangerously-skip-permissions "$SKILL_NAME" ${WORK_ITEM_IDS:-}
fi

exec opencode serve --hostname "${OPENCODE_HOSTNAME:-0.0.0.0}" --port "${OPENCODE_PORT:-4096}"
