import {
  pgTable,
  uuid,
  text,
  boolean,
  timestamp,
  varchar,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { user } from "./auth";

// Legacy table (created in an earlier migration). Kept to avoid interactive rename prompts in drizzle-kit.
// New code should use `telegram_users` below.
export const telegramAccounts = pgTable(
  "telegram_accounts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    // Telegram IDs can exceed JS safe integer limits; store them as text.
    chatId: text("chat_id").notNull(),
    telegramUserId: text("telegram_user_id"),

    username: varchar("username", { length: 64 }),
    firstName: varchar("first_name", { length: 255 }),
    lastName: varchar("last_name", { length: 255 }),

    linkedAt: timestamp("linked_at", { withTimezone: true }).defaultNow().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    userIdUnique: uniqueIndex("telegram_accounts_user_id_unique").on(t.userId),
    chatIdUnique: uniqueIndex("telegram_accounts_chat_id_unique").on(t.chatId),
  })
);

// Telegram user (chat) linked to an Almirant user
export const telegramUsers = pgTable(
  "telegram_users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    // Telegram IDs can exceed JS safe integer limits; store them as text.
    chatId: text("chat_id").notNull(),
    telegramUserId: text("telegram_user_id"),

    username: varchar("username", { length: 64 }),
    firstName: varchar("first_name", { length: 255 }),
    lastName: varchar("last_name", { length: 255 }),

    linkedAt: timestamp("linked_at", { withTimezone: true }).defaultNow().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    userIdUnique: uniqueIndex("telegram_users_user_id_unique").on(t.userId),
    chatIdUnique: uniqueIndex("telegram_users_chat_id_unique").on(t.chatId),
  })
);

// Short-lived linking code generated by the web app and sent to the bot
export const telegramLinkCodes = pgTable(
  "telegram_link_codes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    // SHA-256 hash of the code (never store the raw code)
    codeHash: text("code_hash").notNull(),

    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    codeHashUnique: uniqueIndex("telegram_link_codes_code_hash_unique").on(t.codeHash),
    userIdIdx: index("telegram_link_codes_user_id_idx").on(t.userId),
  })
);

// Per-user notification preferences for Telegram
export const telegramNotificationSettings = pgTable(
  "telegram_notification_settings",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    enabled: boolean("enabled").notNull().default(true),

    notifyWorkItemMoved: boolean("notify_work_item_moved").notNull().default(true),
    notifyWorkItemAssigned: boolean("notify_work_item_assigned").notNull().default(true),
    notifyWorkItemDone: boolean("notify_work_item_done").notNull().default(true),
    notifyReviewCompleted: boolean("notify_review_completed").notNull().default(true),
    notifySprintClosed: boolean("notify_sprint_closed").notNull().default(true),
    notifyUserActions: boolean("notify_user_actions").notNull().default(true),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    userIdUnique: uniqueIndex("telegram_notification_settings_user_id_unique").on(t.userId),
  })
);

export type TelegramLinkCode = typeof telegramLinkCodes.$inferSelect;
export type NewTelegramLinkCode = typeof telegramLinkCodes.$inferInsert;
export type TelegramUser = typeof telegramUsers.$inferSelect;
export type NewTelegramUser = typeof telegramUsers.$inferInsert;
export type TelegramAccount = typeof telegramAccounts.$inferSelect;
export type NewTelegramAccount = typeof telegramAccounts.$inferInsert;
export type TelegramNotificationSettings = typeof telegramNotificationSettings.$inferSelect;
export type NewTelegramNotificationSettings = typeof telegramNotificationSettings.$inferInsert;
