import {
  canonicalStringifyRuntimeCapabilityValue,
  runtimeCapabilityRegistry,
} from "../backend/packages/shared/src/agents/runtime-capability-registry";

const projectRoot = `${import.meta.dir}/..`;

export const runtimeCapabilityProjectionPaths = {
  generatedTypescript:
    `${projectRoot}/backend/packages/shared/src/agents/runtime-capability-projection.generated.ts`,
  frontendJson:
    `${projectRoot}/frontend/src/generated/runtime-capability-projection.v1.json`,
} as const;

export interface RuntimeCapabilityProjectionArtifacts {
  readonly generatedTypescript: string;
  readonly frontendJson: string;
}

const calculateProjectionHashWithBun = (): string => {
  const { hash: _hash, ...payload } = runtimeCapabilityRegistry.projection;
  const canonicalPayload = canonicalStringifyRuntimeCapabilityValue(payload);
  const digest = new Bun.CryptoHasher("sha256")
    .update(canonicalPayload)
    .digest("hex");
  return `sha256:${digest}`;
};

export const buildRuntimeCapabilityProjectionArtifacts =
  (): RuntimeCapabilityProjectionArtifacts => {
    const projection = runtimeCapabilityRegistry.projection;
    const independentHash = calculateProjectionHashWithBun();
    if (independentHash !== projection.hash) {
      throw new Error(
        `runtime capability projection hash mismatch: registry=${projection.hash}, generator=${independentHash}`,
      );
    }

    const canonicalJson = canonicalStringifyRuntimeCapabilityValue(projection, 2);
    return {
      generatedTypescript: [
        "// This file is generated by scripts/generate-runtime-capability-projection.ts.",
        "// Do not edit it by hand; update runtime-capability-registry.ts and regenerate.",
        `export const runtimeCapabilityProjection = ${canonicalJson} as const;`,
        "",
        "export type RuntimeCapabilityProjectionGenerated =",
        "  typeof runtimeCapabilityProjection;",
        "",
      ].join("\n"),
      frontendJson: `${canonicalJson}\n`,
    };
  };

export const assertRuntimeCapabilityProjectionArtifactsCurrent = (
  actual: RuntimeCapabilityProjectionArtifacts,
): void => {
  const expected = buildRuntimeCapabilityProjectionArtifacts();
  if (actual.generatedTypescript !== expected.generatedTypescript) {
    throw new Error(
      "backend/packages/shared/src/agents/runtime-capability-projection.generated.ts is stale; run bun run runtime-capabilities:generate",
    );
  }
  if (actual.frontendJson !== expected.frontendJson) {
    throw new Error(
      "frontend/src/generated/runtime-capability-projection.v1.json is stale; run bun run runtime-capabilities:generate",
    );
  }
};

const readArtifact = async (path: string): Promise<string> => {
  const file = Bun.file(path);
  return (await file.exists()) ? file.text() : "";
};

export const checkRuntimeCapabilityProjection = async (): Promise<void> => {
  const [generatedTypescript, frontendJson] = await Promise.all([
    readArtifact(runtimeCapabilityProjectionPaths.generatedTypescript),
    readArtifact(runtimeCapabilityProjectionPaths.frontendJson),
  ]);
  assertRuntimeCapabilityProjectionArtifactsCurrent({
    generatedTypescript,
    frontendJson,
  });
};

export const generateRuntimeCapabilityProjection = async (): Promise<void> => {
  const artifacts = buildRuntimeCapabilityProjectionArtifacts();
  await Promise.all([
    Bun.write(
      runtimeCapabilityProjectionPaths.generatedTypescript,
      artifacts.generatedTypescript,
    ),
    Bun.write(runtimeCapabilityProjectionPaths.frontendJson, artifacts.frontendJson),
  ]);
};

const main = async (): Promise<void> => {
  const args = process.argv.slice(2);
  if (args.some((arg) => arg !== "--check")) {
    throw new Error(`unsupported argument: ${args.join(" ")}`);
  }

  if (args.includes("--check")) {
    await checkRuntimeCapabilityProjection();
    console.log("Runtime capability projection is current.");
    return;
  }

  await generateRuntimeCapabilityProjection();
  console.log("Generated runtime capability projection artifacts.");
};

if (import.meta.main) {
  await main();
}
