/**
 * Tests for startPlanningSessionSend — the WS-connect race guard.
 *
 * Regression: the very first message of a brand-new /plan session was silently
 * dropped when the input was submitted before the WebSocket finished its
 * handshake ("[planning] startSession skipped: WS not connected"), while the
 * title still got generated by a separate REST call. The WS transport already
 * queues-and-flushes on reconnect, so the send must be forwarded — never
 * dropped — on a transient disconnect. It only bails when there is no transport
 * context at all.
 */
import { describe, expect, it } from "bun:test";
import { startPlanningSessionSend } from "./use-planning-session";
import type { WsClientMessage } from "@/domains/shared/domain/ws-types";

const makeTransport = (isConnected: boolean) => {
  const sent: WsClientMessage[] = [];
  return {
    transport: {
      isConnected,
      sendMessage: (message: WsClientMessage) => {
        sent.push(message);
      },
    },
    sent,
  };
};

/** Narrow a captured message to the planning:start variant for assertions. */
const asPlanningStart = (message: WsClientMessage | undefined) =>
  message as Extract<WsClientMessage, { type: "planning:start" }>;

describe("startPlanningSessionSend", () => {
  it("forwards planning:start to the transport even when the WS is not yet connected", () => {
    const { transport, sent } = makeTransport(false);
    let streamingStarted = false;

    const forwarded = startPlanningSessionSend(
      transport,
      { sessionId: "sess-1", userMessage: "Hola" },
      () => {
        streamingStarted = true;
      },
    );

    // The message must NOT be dropped just because the socket is mid-handshake.
    expect(forwarded).toBe(true);
    expect(streamingStarted).toBe(true);
    expect(sent).toHaveLength(1);

    const msg = asPlanningStart(sent[0]);
    expect(msg.type).toBe("planning:start");
    expect(msg.clientActionId).toBeTruthy();
    expect(msg.payload).toMatchObject({ sessionId: "sess-1", userMessage: "Hola" });
  });

  it("forwards planning:start when the WS is already connected", () => {
    const { transport, sent } = makeTransport(true);

    const forwarded = startPlanningSessionSend(
      transport,
      { sessionId: "sess-2", userMessage: "Arranca" },
      () => {},
    );

    expect(forwarded).toBe(true);
    expect(sent).toHaveLength(1);
    expect(asPlanningStart(sent[0]).payload).toMatchObject({
      sessionId: "sess-2",
      userMessage: "Arranca",
    });
  });

  it("includes seedIds and agentConfig in the payload only when provided", () => {
    const { transport, sent } = makeTransport(false);

    startPlanningSessionSend(
      transport,
      {
        sessionId: "sess-3",
        userMessage: "Con seeds",
        seedIds: ["seed-a", "seed-b"],
        agentConfig: { provider: "anthropic", codingAgent: "claude-code", model: "claude-opus-4-8" },
      },
      () => {},
    );

    expect(asPlanningStart(sent[0]).payload as Record<string, unknown>).toEqual({
      sessionId: "sess-3",
      userMessage: "Con seeds",
      seedIds: ["seed-a", "seed-b"],
      provider: "anthropic",
      codingAgent: "claude-code",
      model: "claude-opus-4-8",
    });
  });

  it("omits empty seedIds and partial agentConfig keys from the payload", () => {
    const { transport, sent } = makeTransport(true);

    startPlanningSessionSend(
      transport,
      {
        sessionId: "sess-4",
        userMessage: "Sin extras",
        seedIds: [],
        agentConfig: { model: "claude-sonnet-5" },
      },
      () => {},
    );

    expect(asPlanningStart(sent[0]).payload as Record<string, unknown>).toEqual({
      sessionId: "sess-4",
      userMessage: "Sin extras",
      model: "claude-sonnet-5",
    });
  });

  it("bails without sending or starting streaming when there is no transport context", () => {
    let streamingStarted = false;

    const forwarded = startPlanningSessionSend(
      null,
      { sessionId: "sess-5", userMessage: "Sin WS" },
      () => {
        streamingStarted = true;
      },
    );

    expect(forwarded).toBe(false);
    expect(streamingStarted).toBe(false);
  });
});
