import { chmod, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { JobLogLine, SpawnResult } from "./types";
import { spawnCmd } from "./spawn";

const HOSTNAME_RE = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;
const TAG_RE = /^tag:[a-z0-9](?:[a-z0-9-]{0,62})$/;
const ENV_FILE = "data/tailscale-db.env";
const OVERRIDE_FILE = "docker-compose.tailscale-db.override.yml";
const TAILSCALE_VOLUME = "almirant-prod_tailscale_db_state";

export type TailnetDbAuth =
  | { method: "auth_key"; authKey: string }
  | { method: "oauth_client"; oauthClientId: string; oauthClientSecret: string };

export interface TailnetDbApplyPayload {
  hostname: string;
  tag: string;
  auth: TailnetDbAuth;
}

export interface TailnetDbContext {
  repoPath: string;
  composeFile: string;
  envFile: string;
  onLog?: (line: JobLogLine) => void;
}

export interface TailnetDbRuntimeStatus {
  configured: boolean;
  online: boolean;
  hostname: string | null;
  tailnetName: string | null;
  tailscaleIp: string | null;
  tailscaleServiceState: string | null;
  proxyServiceState: string | null;
  error: string | null;
}

interface ComposePsRow {
  Service?: string;
  State?: string;
  Health?: string | null;
  ExitCode?: number | string | null;
}

const nowIso = (): string => new Date().toISOString();

const systemLog = (ctx: TailnetDbContext, text: string): void => {
  ctx.onLog?.({ timestamp: nowIso(), source: "system", text });
};

const validate = (payload: TailnetDbApplyPayload): void => {
  if (!HOSTNAME_RE.test(payload.hostname)) {
    throw new Error("Invalid Tailscale hostname");
  }
  if (!TAG_RE.test(payload.tag)) {
    throw new Error("Invalid Tailscale tag");
  }
  if (payload.auth.method === "auth_key") {
    if (!payload.auth.authKey.startsWith("tskey-auth-")) {
      throw new Error("Invalid Tailscale auth key prefix");
    }
    return;
  }
  if (!payload.auth.oauthClientId.trim()) {
    throw new Error("Missing Tailscale OAuth client ID");
  }
  if (!payload.auth.oauthClientSecret.startsWith("tskey-client-")) {
    throw new Error("Invalid Tailscale OAuth client secret prefix");
  }
};

const escapeEnv = (value: string): string =>
  JSON.stringify(value).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");

const envContent = (payload: TailnetDbApplyPayload): string => {
  const lines = [
    "# Generated by Almirant. Do not commit this file.",
    `TAILSCALE_DB_AUTH_METHOD=${escapeEnv(payload.auth.method)}`,
    `TS_HOSTNAME=${escapeEnv(payload.hostname)}`,
    `TS_EXTRA_ARGS=${escapeEnv(`--advertise-tags=${payload.tag}`)}`,
    `TS_STATE_DIR=${escapeEnv("/var/lib/tailscale")}`,
    `TS_AUTH_ONCE=${escapeEnv("true")}`,
    `TS_USERSPACE=${escapeEnv("false")}`,
  ];

  if (payload.auth.method === "auth_key") {
    lines.push(`TS_AUTHKEY=${escapeEnv(payload.auth.authKey)}`);
  } else {
    lines.push(`TS_CLIENT_ID=${escapeEnv(payload.auth.oauthClientId)}`);
    lines.push(`TS_CLIENT_SECRET=${escapeEnv(payload.auth.oauthClientSecret)}`);
  }

  return `${lines.join("\n")}\n`;
};

const writeTailnetEnv = async (
  ctx: TailnetDbContext,
  payload: TailnetDbApplyPayload,
): Promise<void> => {
  validate(payload);
  const path = join(ctx.repoPath, ENV_FILE);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, envContent(payload), { mode: 0o600 });
  await chmod(path, 0o600);
  systemLog(ctx, `Wrote ${ENV_FILE} with redacted Tailscale credentials`);
};

const composeArgs = (ctx: TailnetDbContext): string[] => [
  "compose",
  "-f",
  ctx.composeFile,
  "-f",
  OVERRIDE_FILE,
  "--env-file",
  ctx.envFile,
];

const runDocker = (
  args: string[],
  ctx: TailnetDbContext,
  timeoutMs: number,
): Promise<SpawnResult> =>
  spawnCmd(["docker", ...args], {
    cwd: ctx.repoPath,
    onLog: ctx.onLog,
    timeoutMs,
  });

export const applyTailnetDb = async (
  ctx: TailnetDbContext,
  payload: TailnetDbApplyPayload,
): Promise<SpawnResult> => {
  await writeTailnetEnv(ctx, payload);
  systemLog(ctx, "Starting Tailscale DB sidecar and Postgres tailnet proxy");
  return runDocker(
    [
      ...composeArgs(ctx),
      "up",
      "-d",
      "tailscale-db",
      "postgres-tailnet-proxy",
    ],
    ctx,
    5 * 60_000,
  );
};

export const disableTailnetDb = async (
  ctx: TailnetDbContext,
): Promise<SpawnResult> => {
  systemLog(ctx, "Stopping Tailscale DB sidecar and Postgres tailnet proxy");
  const stop = await runDocker(
    [
      ...composeArgs(ctx),
      "rm",
      "-sf",
      "postgres-tailnet-proxy",
      "tailscale-db",
    ],
    ctx,
    2 * 60_000,
  );

  await rm(join(ctx.repoPath, ENV_FILE), { force: true });
  systemLog(ctx, `Removed ${ENV_FILE}`);

  const volume = await runDocker(
    ["volume", "rm", TAILSCALE_VOLUME],
    ctx,
    30_000,
  );
  if (!volume.ok) {
    systemLog(ctx, `Tailscale state volume was not removed or did not exist: ${volume.stderr.trim()}`);
  }

  return stop;
};

const parsePsRows = (stdout: string): ComposePsRow[] => {
  const trimmed = stdout.trim();
  if (!trimmed) return [];
  if (trimmed.startsWith("[")) {
    try {
      const parsed = JSON.parse(trimmed);
      return Array.isArray(parsed) ? (parsed as ComposePsRow[]) : [];
    } catch {
      return [];
    }
  }
  return trimmed
    .split("\n")
    .map((line) => {
      try {
        return JSON.parse(line) as ComposePsRow;
      } catch {
        return null;
      }
    })
    .filter((row): row is ComposePsRow => row !== null);
};

const serviceState = (rows: ComposePsRow[], service: string): string | null =>
  rows.find((row) => row.Service === service)?.State ?? null;

const parseTailscaleStatus = (stdout: string): Pick<
  TailnetDbRuntimeStatus,
  "online" | "hostname" | "tailnetName" | "tailscaleIp" | "error"
> => {
  try {
    const parsed = JSON.parse(stdout) as Record<string, unknown>;
    const self = parsed.Self as Record<string, unknown> | undefined;
    const currentTailnet = parsed.CurrentTailnet as Record<string, unknown> | undefined;
    const magicDns =
      (currentTailnet?.MagicDNSSuffix as string | undefined) ??
      (parsed.MagicDNSSuffix as string | undefined) ??
      null;
    const ips = Array.isArray(self?.TailscaleIPs) ? self?.TailscaleIPs : [];
    return {
      online: Boolean(self?.Online),
      hostname: (self?.HostName as string | undefined) ?? null,
      tailnetName: magicDns,
      tailscaleIp: typeof ips[0] === "string" ? ips[0] : null,
      error: null,
    };
  } catch (error) {
    return {
      online: false,
      hostname: null,
      tailnetName: null,
      tailscaleIp: null,
      error: error instanceof Error ? error.message : String(error),
    };
  }
};

export const getTailnetDbStatus = async (
  ctx: TailnetDbContext,
): Promise<TailnetDbRuntimeStatus> => {
  const ps = await runDocker(
    [...composeArgs(ctx), "ps", "--format", "json"],
    ctx,
    15_000,
  );
  const rows = ps.ok ? parsePsRows(ps.stdout) : [];
  const tailscaleServiceState = serviceState(rows, "tailscale-db");
  const proxyServiceState = serviceState(rows, "postgres-tailnet-proxy");
  const configured = Boolean(tailscaleServiceState || proxyServiceState);

  if (!configured) {
    return {
      configured: false,
      online: false,
      hostname: null,
      tailnetName: null,
      tailscaleIp: null,
      tailscaleServiceState,
      proxyServiceState,
      error: null,
    };
  }

  const status = await runDocker(
    [...composeArgs(ctx), "exec", "-T", "tailscale-db", "tailscale", "status", "--json"],
    ctx,
    15_000,
  );

  if (!status.ok) {
    return {
      configured,
      online: false,
      hostname: null,
      tailnetName: null,
      tailscaleIp: null,
      tailscaleServiceState,
      proxyServiceState,
      error: status.stderr || status.stdout || "tailscale status failed",
    };
  }

  const parsed = parseTailscaleStatus(status.stdout);
  return {
    configured,
    ...parsed,
    tailscaleServiceState,
    proxyServiceState,
  };
};

export const waitTailnetDbReady = async (
  ctx: TailnetDbContext,
  timeoutMs = 120_000,
): Promise<TailnetDbRuntimeStatus> => {
  const deadline = Date.now() + timeoutMs;
  let latest = await getTailnetDbStatus(ctx);

  while (Date.now() < deadline) {
    latest = await getTailnetDbStatus(ctx);
    if (latest.online && latest.proxyServiceState === "running") return latest;
    await new Promise((resolve) => setTimeout(resolve, 5_000));
  }

  return latest;
};
